version: "3.8"

services:
  database:
    image: postgres:14.6
    container_name: plataforma_pescarte_database
    environment:
      - POSTGRES_USER=peapescarte
      - POSTGRES_PASSWORD=peapescarte
    ports:
      - 5432:5432
    volumes:
      - .postgres:/var/lib/postgresql/data
