version: "3.8"

services:
  pescarte:
    build:
      context: .
      target: builder
    image: pescarte
    command: [ "mix", "phx.server" ]
    container_name: plataforma_pescarte
    ports:
      - 4000:4000
      - 4001:4001
    depends_on:
      - database
    env_file:
      - .env-sample

  database:
    image: postgres:14.6
    container_name: plataforma_pescarte_database
    environment:
      - POSTGRES_USER=peapescarte
      - POSTGRES_PASSWORD=peapescarte
    ports:
      - 5432:5432
    volumes:
      - .postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U peapescarte" ]
      interval: 5s
      timeout: 2s
      retries: 1
